build_bundles: Ignore more packages that exist only on pypi
adafruit/circuitpython-build-tools pull request #90
Opened 2022-07-18 17:59 UTC by jepler

…and sort the existing list and use 'normalized' names

The implementation of normalize_dist_name is taken from pipkin. @aivarannamaa hopefully you can update this list once this PR is confirmed and merged.

@ladyada pipkin copies this list so we should make sure it's up to date on our end!

This list is based on all lines we list in a "requirements.txt" in the adafruit bundle, minutes the ones named adafruit-circuitpython-. Plus numpy and scipy which aren't actually _USED_ at this time, but are added speculatively since dual-purpose code can work with ulab or with numpy.

2022-07-18 18:26 UTC, makermelissa approved these changes
Looks good. Thanks.

2022-07-18 18:28 UTC, makermelissa requested changes
Hmm, I just noticed you had adafruit_circuitpython_busdevice. Is this not a CircuitPython library? Or perhaps it's always built in now so are we just not using it anymore?

2022-07-18 20:02 UTC, makermelissa approved these changes

2022-07-18 20:02 UTC, merged

2022-07-20 05:38 UTC, aivarannamaa commented
To be clear -- is it OK if `pipkin` always installs `adafruit_bus_device` if it's specified as dependency and simply ignores the warning at https://pypi.org/project/adafruit-circuitpython-busdevice/#description:

> If both the builtin and add-on adafruit_bus_device packages are present, then some libraries that require this package _might_ have problems importing it.

?

Do you know what exactly could this potential problem be?