Allow bundles to be skipped
adafruit/circuitpython-build-tools pull request #97
Opened 2023-07-11 01:51 UTC by tekktrik

Allows bundles to be skipped from being built.  This is useful when libraries that do not need specific bundles (e.g., `circuitpython_typing` does not need `.mpy` bundles) are built.

2023-07-11 01:51 UTC, tekktrik commented
Needed to close out https://github.com/adafruit/Adafruit_CircuitPython_Typing/issues/34

2023-07-25 16:18 UTC, jepler requested changes

2023-07-25 16:18 UTC, jepler commented on circuitpython_build_tools/scripts/build_bundles.py
> +@click.option('--ignore', default="", help="Bundles to ignore building")
I'm not tickled about the separator being `", "` since this requires shell quoting `--ignore "py, mpy"` and is easy to get wrong, `--ignore py,mpy` is an undiagnosed error.

If you use `@click.option('--ignore', '-i', multiple=True, type=click.Choice(["py", "mpy", "json"]))` then you don't have to do the parsing, you just give zero or more `--ignore` arguments, and errors are detected.

2023-07-25 18:26 UTC, tekktrik commented on circuitpython_build_tools/scripts/build_bundles.py
> +@click.option('--ignore', default="", help="Bundles to ignore building")
Good catch!  I also felt not great about that, but your suggestion is MUCH more elegant.  I'll fix this up this evening!

2023-07-28 01:13 UTC, jepler approved these changes
thanks!

2023-07-28 01:14 UTC, merged